version: "3"

services:
  #frontend:
  #  build: ./frontend
  #  ports:
  #    - 3000:3000
  #  depends_on:
  #    - solr
  #  volumes:
  #    - ./frontend/src/:/frontend/src/

  #nginx:
  #  build: ./reverse_proxy
  #  ports:
  #    - 9000:9000
  #  depends_on:
  #    - solr

  solr:
    build: ./solr
    container_name: solr
    env_file:
      - solr/.env
    ports: 
      - 8983:8983
    volumes:
      - ./solr/solr_config/:/solr_config/
      - ./src/data/search/:/data/
