version: "3"

services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - solr
    volumes:
      - ./frontend/src/:/frontend/src/

  nginx:
    build: ./nginx
    ports:
      - 80:80 
    depends_on:
      - solr

  solr:
    build: ./src
    container_name: solr
    ports: 
      - 8983:8983
    volumes:
      - ./src/solr_config/:/solr_config/
      - ./src/data/search/:/data/
