version: "3"

services:
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - solr
  #   volumes:
  #     - ./frontend/src/:/frontend/src/

  # nginx:
  #   build: ./reverse_proxy
  #   ports:
  #     - 9000:9000
  #   depends_on:
  #     - solr

  solr:
    build: ./server
    container_name: solr
    env_file:
      - server/.env
    ports: 
      - 8983:8983
    volumes:
      - ./server/solr_config/:/solr_config/
      - ./server/data/clean/:/data/
      - ./server/data/search/:/data/
