version: "3"

services:
  nginx:
    build: ./nginx
    ports:
      - 80:80 
    depends_on:
      - solr
  solr:
    build: .
    container_name: solr
    ports: 
      - 8983:8983
    volumes:
      - ./solr_config/:/solr_config/
      - ./data/search/:/data/